from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

@app.route('/api/generate-layout', methods=['POST'])
def generate_layout():
    # Mock layout data
    mock_layout = {
        "id": 1,
        "name": "Sample Layout",
        "image": "/assets/images/layout1.png",
        "description": "A sample layout generated by the AI engine."
    }
    return jsonify(mock_layout)

if __name__ == '__main__':
    app.run(debug=True)
